import { useState } from "react";
import { borrowers, type BorrowerFixture } from "./mockCreditData";
import { requestLoan, type RequestLoanResult } from "./ghostCreditApi";

const MIN_SCORE = 700;
const LOAN_AMOUNT = 500;

type Props = {
  onLoanApproved: (borrower: BorrowerFixture, amount: number, contractAddress: string) => void;
};

export default function BorrowerView({ onLoanApproved }: Props) {
  const [selectedId, setSelectedId] = useState(borrowers[0].id);
  const [proving, setProving] = useState(false);
  const [result, setResult] = useState<RequestLoanResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const borrower = borrowers.find((b) => b.id === selectedId)!;

  // Calls the real requestLoan circuit on a deployed Ghost Credit contract
  // via the local dev API (src/server.ts) — a real ZK proof is generated by
  // the proof server for this call, which is why it takes several seconds.
  const runProof = async () => {
    setProving(true);
    setResult(null);
    setError(null);
    try {
      const outcome = await requestLoan(
        borrower.id,
        { score: borrower.score, liquidationCount: borrower.liquidationCount, accountAgeMonths: borrower.accountAgeMonths },
        LOAN_AMOUNT,
      );
      setResult(outcome);
      if (outcome.approved) onLoanApproved(borrower, LOAN_AMOUNT, outcome.contractAddress);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setProving(false);
    }
  };

  return (
    <div className="panel">
      <h2>Borrower</h2>
      <p className="dim">Connect a wallet and request a loan.</p>

      <label>
        Wallet
        <select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}>
          {borrowers.map((b) => (
            <option key={b.id} value={b.id}>
              {b.displayName}
            </option>
          ))}
        </select>
      </label>

      <div className="private-box">
        <strong>Private inputs (never leave your device)</strong>
        <ul>
          <li>Score: {borrower.score}</li>
          <li>Liquidations: {borrower.liquidationCount}</li>
          <li>Account age: {borrower.accountAgeMonths} months</li>
        </ul>
      </div>

      <button onClick={runProof} disabled={proving}>
        {proving ? "Generating proof..." : `Request ${LOAN_AMOUNT} USDC loan (needs score ≥ ${MIN_SCORE})`}
      </button>

      {result?.approved && (
        <p className="ok">
          Proof verified on-chain. Loan approved at contract {result.contractAddress.slice(0, 12)}…
        </p>
      )}
      {result && !result.approved && <p className="fail">Rejected on-chain: {result.reason}</p>}
      {error && <p className="fail">Request failed: {error} (is the dev API running? see README)</p>}
    </div>
  );
}
